### ISSUE TITLE
Missing 4.0.5 Release

### ISSUE THREAD

**Issue by karolsteve** [instaclustr/cassandra-lucene-index#11]
Is it possible to use 4.0.0 release on 4.0.5 cassandra version ?

**Comment by smiklosovic** [comment]
@karolsteve It should be possible. Patch releases should be backward compatible.

here you have 4.0.4. That one is the closest to 4.0.5 so the chance all will be working is the biggest.

https://github.com/instaclustr/cassandra-lucene-index/releases/tag/cassandra-4.0.4-1.0.0
