### ISSUE TITLE
Get count of matching results

### ISSUE THREAD

**Issue by Telavian** [instaclustr/cassandra-lucene-index#2]
I just started investigating this project after having some issues with ElasticSearch.
After doing some prototype work I have to say this project is nothing short of amazing.
It incorporates directly into Cassandra and makes so many hard things simple.

I seriously hope I don't find any showstoppers because I really want this project to work.

In some of my search locations I like to show the matches along with the total possible data items.
However I am not sure how to retrieve the total count of document matches along with the matching data.
It appears I could do 1 query for the data and another for the counts. However this seems like a double use of resources.

```
Select * from tweets;
Select count(*) from tweets;
```

Is there a way to do it without the additional count query?

**Comment by slater-ben** [comment]
Glad you are finding this useful. I don't believe it is possible to do a select * and a count(*) in a single operation.

I would not that Cassandra is largely intended for operational big data uses cases (ie lots of relatively small inserts and selects from vast data sets) so unbounded selects can be a bit of a red flag that it may not be the best solution for your use case.

**Comment by Telavian** [comment]
You are referring to select * instead of select col1, col2?

**Comment by slater-ben** [comment]
select * is fine. select without any where conditions is the concern. You nearly always want your queries to be filtered by the partition key (even with the use of a secondary index such as this one).

**Comment by Telavian** [comment]
Ok. I understand. Thanks for the guidance.
Cassandra is certainly something hard to wrap your mind around instead of a RDBMS however when you do it is pretty simple and powerful.
