### ISSUE TITLE
Problem to build cassandra-lucene-index 3.11.10.0

### ISSUE THREAD

**Issue by JoaoPagotto** [instaclustr/cassandra-lucene-index#4]
-------------------------------------------------------------------------------
-- Check Java Version

java -version
  java version "1.8.0_291"
  Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
  Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

-------------------------------------------------------------------------------
-- Check Java Compiler Version

javac -version
  javac 1.8.0_291

-------------------------------------------------------------------------------
-- Check Maven Version

mvn -version
  Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
  Maven home: C:\src\apache-maven-3.8.1\bin\..

-------------------------------------------------------------------------------
-- Process checkout cassandra-lucene-index

git clone https://github.com/instaclustr/cassandra-lucene-index.git
cd cassandra-lucene-index
git checkout 3.11.10.0
mvn clean package

-------------------------------------------------------------------------------
-- Error

C:\Users\user\AppData\Local\Temp\scala-maven-plugin-compiler-bridge-sources7168432815935638631\scala\ZincCompat.scala:23: error: type mismatch;
 found   : pf.type (with underlying type scala.ZincCompat.PlainNioFile)
 required: ?{def getClass: ?}
    val f = pf.getClass.getDeclaredField("nioPath") // it's not val'd in 2.12 :-/
            ^
two errors found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Cassandra Lucene index 3.11.10.0:
[INFO]
[INFO] Cassandra Lucene index ............................. SUCCESS [  6.662 s]
[INFO] Cassandra Lucene Index builder ..................... SUCCESS [ 12.936 s]
[INFO] Cassandra Lucene Index plugin ...................... FAILURE [ 16.341 s]
[INFO] Cassandra Lucene Index distribution ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.255 s
[INFO] Finished at: 2021-05-06T09:54:57-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.5.1:compile (scala-compile-first) on project cassandra-lucene-index-plugin: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.5.1:compile failed.: CompileFailed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :cassandra-lucene-index-plugin

-------------------------------------------------------------------------------

**Comment by smiklosovic** [comment]
Hi, 

I am not sure what the problem is, in pom, the version of Scala is 2.12.0.

**Comment by abrucker235** [comment]
I am seeing the same issue any resolution to this?

**Comment by JoaoPagotto** [comment]
> I am seeing the same issue any resolution to this?

Yes see my solution:

set path=%path%;c:\src\apache-maven-3.8.1\bin
cd \src

git clone https://github.com/instaclustr/cassandra-lucene-index
cd cassandra-lucene-index

*** open all pom.xml and *** 
*** replace text 3.11.3 to 3.11.10 *** 

mvn clean package -Ppatch -Dcassandra_home=c:\src\apache-cassandra-3.11.10

this c:\src\apache-cassandra-3.11.10 is directory of install cassandra ;)

**Comment by smiklosovic** [comment]
@JoaoPagotto do you still use that patch profile? I have removed it from cassandra-4.0-rc1 ... ooops :D It is just about copying that jar file to `libs` dir of Cassandra, that is all magic there.

**Comment by smiklosovic** [comment]
I have moved these profiles back into plugin/pom.xml - into branch cassandra-4.0-rc1.

**Comment by smiklosovic** [comment]
this fixes it https://github.com/instaclustr/cassandra-lucene-index/pull/13
