### ISSUE TITLE
Compatibility with Cassandra 4.0

### ISSUE THREAD

**Issue by JoaoPagotto** [instaclustr/cassandra-lucene-index#5]
Sorry if this is not the right place for my question. 
Will the cassandra-lucene-index support the Cassandra 4.0 version? 
Hugs.

**Comment by smiklosovic** [comment]
We are working on it but right now it is pretty much broken.

**Comment by smiklosovic** [comment]
@JoaoPagotto we are moving towards 4.0 compatibility very fast. It is compatible on 99%. Stay tuned!

**Comment by JoaoPagotto** [comment]
@smiklosovic what excellent news, thank you very much, I will be attentive. :D

**Comment by smiklosovic** [comment]
Hi @JoaoPagotto 

you can build branch cassandra-4.0-rc1 as `./mvnw clean install`

I will release it very soon (probably tomorrow).

Regards
