### ISSUE TITLE
Lucene Plugin installation error for  Cassandra 4.0.7 in Ubuntu 22.04

### ISSUE THREAD

**Issue by cssndrthrift** [instaclustr/cassandra-lucene-index#9]
Hi,

While testing for Lucene plugin for my Cassandra version 4.0.7 in Ubuntu 22.04
I faced error in 3rd step i.e. 

~/cassandra-lucene-index$ git checkout 4.0.7
error: pathspec '4.0.7' did not match any file(s) known to git

![image](https://user-images.githubusercontent.com/121041937/219656983-d6d779a6-a97a-434b-820b-be15291516bb.png)

Subsequently below step failed also

mvn clean package

![image](https://user-images.githubusercontent.com/121041937/219657355-b3fddd01-65c3-482b-840b-1914079f5f2f.png)

I am running wrong command,kindly correct me

**Comment by ErickRamirezAU** [comment]
Noting here that this was also posted on https://dba.stackexchange.com/questions/325449/.

@cssndrthrift I don't see a tag or branch called `4.0.7` but there is a branch called `cassandra-4.0.7`. Could try to build with it?

@smiklosovic if you have some spare cycles, are you able to assist. Cheers! 🍻

**Comment by smiklosovic** [comment]
Yes it has to be cassandra-4.0.7
